[project]
name = "sa-traffic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dimod>=0.12.21",
    "matplotlib>=3.10.7",
]
